import { FolderKanban, Zap, PenLine, Briefcase, Quote, LayoutGrid, Mail } from "lucide-react";

export const aboutFields = [
  { name: "name", label: "Your name", type: "text", required: true },
  { name: "title", label: "Job title", type: "text", placeholder: "Full Stack Developer" },
  { name: "bio", label: "Bio", type: "textarea" },
  { name: "avatar", label: "Profile photo", type: "image" },
  { name: "resumeUrl", label: "Resume link (Google Drive etc.)", type: "text" },
  { name: "email", label: "Email", type: "text" },
  { name: "location", label: "Location", type: "text", placeholder: "Bengaluru, India" },
  { name: "github", label: "GitHub URL", type: "text" },
  { name: "linkedin", label: "LinkedIn URL", type: "text" },
  { name: "twitter", label: "Twitter / X URL", type: "text" },
];

export const resources = [
  {
    key: "projects",
    label: "Projects",
    icon: FolderKanban,
    titleField: "title",
    imageField: "image",
    subtitle: (i) => (i.techStack || []).join(" · "),
    fields: [
      { name: "title", label: "Title", type: "text", required: true },
      { name: "description", label: "Description", type: "textarea" },
      { name: "image", label: "Screenshot", type: "image" },
      { name: "techStack", label: "Tech stack (comma separated)", type: "tags", placeholder: "React, Node, MongoDB" },
      { name: "liveUrl", label: "Live URL", type: "text" },
      { name: "githubUrl", label: "GitHub URL", type: "text" },
      { name: "featured", label: "Featured project", type: "checkbox" },
      { name: "order", label: "Order (smaller shows first)", type: "number" },
    ],
  },
  {
    key: "skills",
    label: "Skills",
    icon: Zap,
    titleField: "name",
    subtitle: (i) => `${i.category} · ${i.level}%`,
    fields: [
      { name: "name", label: "Skill name", type: "text", required: true, placeholder: "React" },
      { name: "category", label: "Category", type: "text", placeholder: "Frontend" },
      { name: "level", label: "Level (0 to 100)", type: "number" },
    ],
  },
  {
    key: "blogs",
    label: "Blog",
    icon: PenLine,
    titleField: "title",
    imageField: "coverImage",
    subtitle: (i) => (i.published ? "Published" : "Draft"),
    fields: [
      { name: "title", label: "Title", type: "text", required: true },
      { name: "excerpt", label: "Short summary", type: "textarea" },
      { name: "content", label: "Content", type: "textarea", rows: 10 },
      { name: "coverImage", label: "Cover image", type: "image" },
      { name: "published", label: "Published (visible to visitors)", type: "checkbox" },
    ],
  },
  {
    key: "experience",
    label: "Experience",
    icon: Briefcase,
    titleField: "role",
    subtitle: (i) => `${i.company} · ${i.startDate || ""} – ${i.endDate || "Present"}`,
    fields: [
      { name: "role", label: "Role", type: "text", required: true },
      { name: "company", label: "Company", type: "text", required: true },
      { name: "startDate", label: "Start date", type: "text", placeholder: "Jun 2026" },
      { name: "endDate", label: "End date (empty = Present)", type: "text", placeholder: "Aug 2026" },
      { name: "description", label: "What you did", type: "textarea" },
      { name: "order", label: "Order (smaller shows first)", type: "number" },
    ],
  },
  {
    key: "testimonials",
    label: "Testimonials",
    icon: Quote,
    titleField: "name",
    imageField: "avatar",
    subtitle: (i) => i.role,
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "role", label: "Role / Company", type: "text" },
      { name: "message", label: "What they said", type: "textarea", required: true },
      { name: "avatar", label: "Photo", type: "image" },
    ],
  },
  {
    key: "services",
    label: "Services",
    icon: LayoutGrid,
    titleField: "title",
    subtitle: (i) => i.description,
    fields: [
      { name: "title", label: "Service", type: "text", required: true },
      { name: "description", label: "Description", type: "textarea" },
    ],
  },
  {
    key: "messages",
    label: "Messages",
    icon: Mail,
    titleField: "name",
    readOnly: true,
    subtitle: (i) => `${i.email} — ${i.message}`,
    fields: [],
  },
];